wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.2
epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.001
n_tasks:
  desc: null
  value: 2
